services:
  - type: web
    name: mini-chat-gemini
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: GOOGLE_API_KEY
        value: AIzaSyDkBE0ciGqherga2M76C1cRVMG_p_1ITOc
