services:
  - type: web
    name: mini-chatgpt
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: OPENAI_API_KEY
        value: sk-tu-clave-aqui
